on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        version: v1.29
        args: --issues-exit-code=0 -e "SA1019"